name: FakeDimension
main: fakedimension.FakeDimension
api-version: '1.16'
depend: [ProtocolLib]
version: ${project.version}
authors:
    - _Shevchik_
    - Narwhal
commands:
    fakedimension:
        description: Reload command for FakeDimension
        usage: /fakedimension reload - reload configuration
