name: FakeDimension
main: fakedimension.FakeDimension
api-version: 1.14
depend: [ProtocolLib]
version: 1.1
author: _Shevchik_
commands:
    fakedimension:
        description: Reload command for FakeDimension
        usage: /fakedimension reload - reload configuration